
USER root
RUN apt install -y unzip
USER pleroma
RUN set -ex; \
    curl -L "https://gitlab.com/soapbox-pub/soapbox/-/jobs/artifacts/develop/download?job=build-production" -o /tmp/soapbox.zip; \
    unzip /tmp/soapbox.zip -d /opt/pleroma/instance; \
    rm /tmp/soapbox.zip
