
USER root
RUN apk install unzip
USER pleroma
RUN set -ex; \
    wget "https://gitlab.com/soapbox-pub/soapbox/-/jobs/artifacts/develop/download?job=build-production" -O /tmp/soapbox.zip; \
    unzip /tmp/soapbox.zip -d /opt/pleroma/instance; \
    rm /tmp/soapbox.zip
