name: Build Soapbox

on:
  push:
    branches: 
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate date string
        id: date
        run: echo "date=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout Pleroma source to ./pleroma
        run: git clone https://git.pleroma.social/pleroma/pleroma.git --depth 1 --branch develop pleroma

      - name: Extend Pleroma Dockerfile
        run: cat >> ./pleroma/Dockerfile < ./soapbox/Dockerfile.extend

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: pleroma/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/lemniskett/soapbox:latest
            ghcr.io/lemniskett/soapbox:${{ steps.date.outputs.date }}

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get deployment scripts
  #       uses: actions/checkout@v3
  #       with:
  #         repository: lemniskett/rancher-api-scripts
          
  #     - name: Execute redeploy.py
  #       run: python3 ./redeploy.py misskey
  #       env:
  #         RANCHER_URL: ${{ secrets.RANCHER_URL }}
  #         RANCHER_CLUSTER: ${{ secrets.RANCHER_CLUSTER }}
  #         RANCHER_NAMESPACE: ${{ secrets.RANCHER_NAMESPACE }}
  #         RANCHER_ACCESS_KEY: ${{ secrets.RANCHER_ACCESS_KEY }}
  #         RANCHER_SECRET_KEY: ${{ secrets.RANCHER_SECRET_KEY }}
