name: Build Alpine OpenRC

on:
  push:
    branches: 
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate date string
        id: date
        run: echo "date=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: alpine-openrc/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/lemniskett/alpine:latest
            ghcr.io/lemniskett/alpine:${{ steps.date.outputs.date }}
